MDScreen:
     name: 'page'
     MDFloatLayout:
        md_bg_color: 218/255, 221/255, 216/255, 1
        Image:
            source: 'assets/trackmood-logo.png'
            size_hint: 0.2, 0.2
            pos_hint: {'center_x': 0.27, 'center_y': 0.75}
        MDLabel:
            text: 'r a c k m o o d'
            font_name: 'Bras Mono'
            font_size: '23sp'
            pos_hint: {'center_x': 0.89, 'center_y': 0.75}
            color: rgba(91, 119, 127, 255)